version: '3'
services:

  app:
    restart: always
    image: laravel:7.1
    volumes:
      - ./:/var/www
      - ./storage/app/public/:/var/www/public/storage
    network_mode: bridge
    environment:
      DB_HOST: "172.16.1.100:3356"
      DB_DATABASE: "susako"
      DB_USERNAME: "susako"
      DB_PASSWORD: "password"
      DB_CONNECTION: "mysql"
      APP_URL: http://susako.dock
      VIRTUAL_HOST: "susako.dock"
      XDEBUG_CONFIG: remote_host=${LOCAL_IP}