version: '3'
services:
  app:
    image: hitalos/laravel:latest
    links:
      - db
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: "db"
      DB_DATABASE: "homestead"
      DB_USERNAME: "susako"
      DB_PASSWORD: "secret"
      DB_CONNECTION: "mysql"
    ports:
        - "80:80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8000:80"
    environment:
      PMA_HOST: "db"
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "demo123"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "susako"
      MYSQL_PASSWORD: "secret"
    ports:
        - "3306:3306"
volumes:
  dbdata: