version: '3'
services:

  app:
    image: esimple/laravel:latest
    volumes:
      - ./public:/var/www/html
      - ./:/var/www
    network_mode: bridge
    environment:
      DB_HOST: "host.docker.internal"
      DB_DATABASE: "susako"
      DB_USERNAME: "susako"
      DB_PASSWORD: "secret"
      DB_CONNECTION: "mysql"
      APP_URL: http://susako.dock
      VIRTUAL_HOST: "susako.dock"
      XDEBUG_CONFIG: remote_host=${LOCAL_IP}